server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:9090/microservices
    username: postgres
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/




