server:
  port: 8084

spring:
  application:
    name: API-GATEWAY



  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: RATING_SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



# okta auth config

okta:
  oauth2:
    issuer: https://dev-98716900.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaf9vozdaKMhBrjf5d7
    client-secret: pWTy5q0nezjG7o4WtcrLYYdjj5m8u2Ugn55kzU-iL3n6FDt9wwztk_P1zF65OCC2
    scopes:
      - openid
      - profile
      - email
      - offline_access



